[package]
name = "candle-layer-norm"
version = "0.0.1"
edition = "2021"

description = "Layer Norm layer for the candle ML framework."

[dependencies]
#candle = { version = "*", package = "candle-core", features = ["cuda"] }
candle = { git = "https://github.com/spiceai/candle.git", version = "0.8", rev = "a84593f1951a4a9083e29257003a8112eb1450da", package = "candle-core", default-features = false }
half = { version = "2.3.1", features = ["num-traits"] }

[build-dependencies]
anyhow = { version = "1", features = ["backtrace"] }
num_cpus = "1.15.0"
rayon = "1.7.0"

[features]
dynamic-linking = []